source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

platform :ios, '10.2'

target 'NumPadExample' do
	pod 'NumPad', :path => '../' 
	pod 'PhoneNumberKit', git: 'https://github.com/oskarirauta/PhoneNumberKit.git'
end
